package cn.nexon.zerovector.core.hook;

public enum HookType {
    DOCUMENT_UPLOAD_START,
    DOCUMENT_UPLOAD_END,
    DOCUMENT_UPLOAD_ERROR,
    
    DOCUMENT_COMPREHEND_START,
    DOCUMENT_COMPREHEND_END,
    DOCUMENT_COMPREHEND_ERROR,
    
    TREE_BUILD_START,
    TREE_BUILD_END,
    TREE_BUILD_ERROR,
    TREE_NODE_CREATED,
    
    NAVIGATION_START,
    NAVIGATION_END,
    NAVIGATION_ERROR,
    NAVIGATION_STEP
}
